config/routes.rb
Rails.application.routes.draw do
  resources :destinations
  get 'welcome/index'
  get 'welcome/loader'
  post 'welcome/builder'
  get 'welcome/random_builder'
  get 'welcome/unclassified_builder'

  resources :welcome
  resources :media
  resources :sources

  root 'welcome#index'
  

end

app/models/destination.rb
class Destination < ActiveRecord::Base
  has_many :relations
  has_many :media, through: :relations

  validates :path, presence: true, uniqueness: true, length: { minimum: 2 }
end

app/models/medium.rb
class Medium < ActiveRecord::Base
  has_many :relations
  has_many :destinations, through: :relations

  accepts_nested_attributes_for :relations,
                                reject_if: :reject_relations,
                                allow_destroy: true
  def reject_relations(attributes)
    attributes['destination_id'].blank?
  end

  validates :filename, presence: true, uniqueness: true, length: { minimum: 2 }
end

app/models/relation.rb
class Relation < ActiveRecord::Base
  belongs_to :medium
  belongs_to :destination
end

app/models/source.rb
class Source < ActiveRecord::Base
  validates :path, presence: true, uniqueness: true, length: { minimum: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    @destinations = Destination.all
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_destination
    @destination = Destination.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def destination_params
    params.require(:destination).permit(:path)
  end
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  before_action :set_medium, only: [:show, :edit, :update, :destroy]

  # GET /media
  # GET /media.json
  def index
    @media = Medium.all
  end

  # GET /media/1
  # GET /media/1.json
  def show
  end

  # GET /media/new
  def new
    @medium = Medium.new
  end

  # GET /media/1/edit
  def edit
  end

  # POST /media
  # POST /media.json
  def create
    @medium = Medium.new(medium_params)

    respond_to do |format|
      if @medium.save
        format.html { redirect_to @medium, notice: 'Medium was successfully created.' }
        format.json { render :show, status: :created, location: @medium }
      else
        format.html { render :new }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /media/1
  # PATCH/PUT /media/1.json
  def update
    respond_to do |format|
      if @medium.update(medium_params)
        format.html { redirect_to @medium, notice: 'Medium was successfully updated.' }
        format.json { render :show, status: :ok, location: @medium }
      else
        format.html { render :edit }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media/1
  # DELETE /media/1.json
  def destroy
    @medium.destroy
    respond_to do |format|
      format.html { redirect_to media_url, notice: 'Medium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_medium
    @medium = Medium.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def medium_params
    params.require(:medium).permit(:filename, :modified_filename,
                                   relations_attributes: [:id, :destination_id, :_destroy])
  end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :set_source, only: [:show, :edit, :update, :destroy]

  # GET /sources
  # GET /sources.json
  def index
    @sources = Source.all
  end

  # GET /sources/1
  # GET /sources/1.json
  def show
  end

  # GET /sources/new
  def new
    @source = Source.new
  end

  # GET /sources/1/edit
  def edit
  end

  # POST /sources
  # POST /sources.json
  def create
    @source = Source.new(source_params)

    respond_to do |format|
      if @source.save
        format.html { redirect_to @source, notice: 'Source was successfully created.' }
        format.json { render :show, status: :created, location: @source }
      else
        format.html { render :new }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sources/1
  # PATCH/PUT /sources/1.json
  def update
    respond_to do |format|
      if @source.update(source_params)
        format.html { redirect_to @source, notice: 'Source was successfully updated.' }
        format.json { render :show, status: :ok, location: @source }
      else
        format.html { render :edit }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1
  # DELETE /sources/1.json
  def destroy
    @source.destroy
    respond_to do |format|
      format.html { redirect_to sources_url, notice: 'Source was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_source
    @source = Source.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def source_params
    params.require(:source).permit(:path)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def show
  end

  def loader
    scan_sources = ScanSources.new
    scan_sources.process
    render 'index'
  end

  def builder
    stick = stick_params
    selector = DefaultSelector.new(stick)
    build_stick = BuildStick.new({ selector: selector, stick: stick })
    build_stick.process
    render 'index'
  end

  def random_builder
    selector = RandomSelector.new
    build_stick = BuildStick.new({ selector: selector })
    build_stick.process
    render 'index'
  end

  def unclassified_builder
    selector = UnclassifiedSelector.new
    build_stick = BuildStick.new({ selector: selector })
    build_stick.process
    render 'index'
  end

  private

  def stick_params
    params.require(:stick) # .permit(:destination)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/destinations/_form.html.haml
= form_for @destination do |f|
  - if @destination.errors.any?
    #error_explanation
      %h2= "#{pluralize(@destination.errors.count, "error")} prohibited this destination from being saved:"
      %ul
        - @destination.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :path
    = f.text_field :path
  .actions
    = f.submit 'Save'

app/views/destinations/edit.html.haml
%h1 Editing destination

= render 'form'

= link_to 'Show', @destination
\|
= link_to 'Back', destinations_path

app/views/destinations/index.html.haml
%h1 Listing destinations
%div{:class => "media"}
  %div{:class => "media-body"}
    %table{:class => "table table-hover"}
      %thead
        %tr
          %th Path
          %th
          %th
          %th

      %tbody
        - @destinations.each do |destination|
          %tr
            %td= destination.path
            %td= link_to 'Show', destination
            %td= link_to 'Edit', edit_destination_path(destination)
            %td= link_to 'Destroy', destination, :method => :delete, :data => { :confirm => 'Are you sure?' }

    %br

    = link_to 'New Destination', new_destination_path

app/views/destinations/new.html.haml
%h1 New destination

= render 'form'

= link_to 'Back', destinations_path

app/views/destinations/show.html.haml
%div{:class => "media"}
  %div{:class => "media-body"}
    %p#notice= notice

    %p
      %b Path:
      = @destination.path
    = link_to 'Edit', edit_destination_path(@destination)
    \|
    = link_to 'Back', destinations_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title VidstickApp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %div{:class => "container"}
      %ul{:class => "nav nav-tabs"}
        %li= link_to 'welcome', welcome_index_path
        %li= link_to 'sources', sources_path
        %li= link_to 'media',   media_path
        %li= link_to 'destinations',   destinations_path
    = yield

app/views/media/_destination_fields.html.haml
.form-inline.clearfix
  .nested-fields
    = f.collection_select :destination_id, Destination.order('path ASC'), :id, :path
    %p = f.input :path, input_html: { class: 'form-input form-control' }
    %p = link_to_remove_association "Remove", f, class: "form-button btn btn-default"

app/views/media/_form.html.haml
= simple_form_for @medium, html: { multipart: true } do |f|
  - if @medium.errors.any?
    #errors
      %p
        = @medium.errors.count
        Prevented this medium froms saving
      %ul
        - @medium.errors.full_messages.each do |msg|
          %li= msg
  .panel-body
    = f.input :filename, input_html: { class: 'form-control' }
    = f.input :modified_filename, input_html: { class: 'form-control' }

    .row
      .col-md-6
        %h3 Destinations
        #relations
          = f.simple_fields_for :relations do |relation|
            = render 'relation_fields', f: relation
          .links
            = link_to_add_association 'Add Destinations', f, :relations, class: "btn btn-default add-button"
      .col-md-6

  = f.button :submit, class: "btn btn-primary"
%button{:onclick => "getElementById('medium_modified_filename').value=getElementById('medium_filename').value"} Refresh Modified filename

app/views/media/_relation_fields.html.haml
.form-inline.clearfix
  .nested-fields
    = f.collection_select :destination_id, Destination.order('path ASC'), :id, :path
    = link_to_remove_association "Remove", f, class: "form-button btn btn-default"

app/views/media/edit.html.haml
%h1 Editing medium

= render 'form'

= link_to 'Show', @medium
\|
= link_to 'Back', media_path

app/views/media/index.html.haml
%h1 Listing media
%div{:class => "media"}
  %div{:class => "media-body"}
    %table{:class => "table table-hover"}
      %thead
        %tr
          %th Filename
          %th Cnt
          %th
          %th
          %th

      %tbody
        - @media.each do |medium|
          %tr
            %td= medium.filename
            %td= medium.destinations.count
            %td= link_to 'Show', medium
            %td= link_to 'Edit', edit_medium_path(medium)
            %td= link_to 'Destroy', medium, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Medium', new_medium_path

app/views/media/new.html.haml
%h1 New medium

= render 'form'

= link_to 'Back', media_path

app/views/media/show.html.haml
%p#notice= notice

%p
  %b Filename:
  = @medium.filename
%p
  %b Modified filename:
  = @medium.modified_filename
#destinations
  %h2 Destinations
  %ul
    - @medium.relations.each do |relation|
      %li= relation.destination_id 
      %li= Destination.find(relation.destination_id).path

= link_to 'Edit', edit_medium_path(@medium)
\|
= link_to 'Back', media_path

app/views/sources/_form.html.haml
= form_for @source do |f|
  - if @source.errors.any?
    #error_explanation
      %h2= "#{pluralize(@source.errors.count, "error")} prohibited this source from being saved:"
      %ul
        - @source.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :path
    = f.text_field :path
  .actions
    = f.submit 'Save'

app/views/sources/edit.html.haml
%h1 Editing source

= render 'form'

= link_to 'Show', @source
\|
= link_to 'Back', sources_path

app/views/sources/index.html.haml
%h1 Listing sources
%div{:class => "media"}
  %div{:class => "media-body"}
    %table{:class => "table table-hover"}
      %thead
        %tr
          %th Path
          %th
          %th
          %th

      %tbody
        - @sources.each do |source|
          %tr
            %td= source.path
            %td= link_to 'Show', source
            %td= link_to 'Edit', edit_source_path(source)
            %td= link_to 'Destroy', source, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Source', new_source_path

app/views/sources/new.html.haml
%h1 New source

= render 'form'

= link_to 'Back', sources_path

app/views/sources/show.html.haml
%p#notice= notice

%p
  %b path:
  = @source.path

= link_to 'Edit', edit_source_path(@source)
\|
= link_to 'Back', sources_path

app/views/welcome/index.html.haml
%h1 Welcome#index
%div{:class => "media"}
  %div{:class => "media-body"}
    .panel-body
      .row
        %p Find me in app/views/welcome/index.html.haml
        .col-md-6
          = link_to 'Load', welcome_loader_path, class: "btn btn-primary"
        .col-md-6
          = simple_form_for :stick, url: welcome_builder_path  do |f|
            .panel-body
              = f.collection_select :destination, Destination.order('path ASC'), :id, :path, 
                                    {:prompt => 'Please select one or many'}, 
                                    {:multiple => true, :size => 15, :style => 'width:50%'}
            = f.button :submit, class: "btn btn-primary"
          %br
          = link_to 'Random builder', welcome_random_builder_path, class: "btn btn-primary"
          %br
          = link_to 'Unclassified builder', welcome_unclassified_builder_path, class: "btn btn-primary"